name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      NX_SOCKET_DIR: /tmp/nx-tmp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.12.14 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
      - name: Get pnpm store directory
        id: npm_cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: steps.npm_cache.outputs.cache-hit != 'true'
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main
      - name: Run build
        run: pnpm nx build prisma-generator-vault
      - name: Migrate
        run: cd packages/prisma-generator-vault && pnpm prisma migrate dev --schema test/prisma/prisma.test.schema
      - name: Lint
        run: pnpm nx lint prisma-generator-vault
      - name: Run Test Suite
        run: pnpm nx test prisma-generator-vault
